// I am developing a project task management web application. What should be the data structure for this or how should it be done?
// Here there will be project description, project status, drag and drop, update, delete, create.
// now create a array of object
export const initialProjects = [
  {
    id: 1,
    title: "Project 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "completed",
    deadline: "2022-12-12",
    requirement: ["React", "Node", "MongoDB"],
    budget: 1000,
    userCreatedId: 1,
  },
  {
    id: 2,
    title: "Project 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "inProgress",
    deadline: "2022-12-12",
    requirement: ["Nextjs", "Node", "MongoDB"],
    budget: 2000,
    userCreatedId: 11,
  },
  {
    id: 3,
    title: "Project 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "notStarted",
    deadline: "2022-12-12",
    requirement: ["Vue", "Node", "MongoDB"],
    budget: 3000,
    userCreatedId: 3,
  },
  {
    id: 4,
    title: "Project 4",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "inProgress",
    deadline: "2022-12-12",
    requirement: ["Angular", "Node", "MongoDB"],
    budget: 4000,
    userCreatedId: 4,
  },
  {
    id: 5,
    title: "Project 5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "completed",
    deadline: "2022-12-12",
    requirement: ["React", "Node", "MongoDB"],
    budget: 5000,
    userCreatedId: 2,
  },
  {
    id: 6,
    title: "Project 6",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "notStarted",
    deadline: "2022-12-12",
    requirement: ["React", "Django", "MongoDB"],
    budget: 2000,
    userCreatedId: 6,
  },
  {
    id: 7,
    title: "Project 7",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "notStarted",
    deadline: "2022-12-12",
    requirement: ["React", "Python", "MongoDB"],
    budget: 3000,
    userCreatedId: 7,
  },
  {
    id: 8,
    title: "Task 8",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "High",
    status: "submitted",
    deadline: "2022-12-12",
    requirement: ["React", "Node", "MongoDB"],
    budget: 1000,
    userCreatedId: 8,
  },
  {
    id: 9,
    title: "Task 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Medium",
    status: "inProgress",
    deadline: "2022-12-12",
    requirement: ["Nextjs", "Node", "MongoDB"],
    budget: 2000,
    userCreatedId: 9,
  },
  {
    id: 10,
    title: "Task 10",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Low",
    status: "notStarted",
    deadline: "2022-12-12",
    requirement: ["React", "PHP", "MySQL"],
    budget: 3000,
    userCreatedId: 10,
  },
  {
    id: 4,
    title: "Task 4",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Hight",
    status: "submitted",
    deadline: "2022-12-12",
    requirement: ["React", "Node", "MySQL"],
    budget: 4000,
    userCreatedId: 4,
  },
  {
    id: 5,
    title: "Task 5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Medium",
    status: "done",
    deadline: "2022-12-12",
    requirement: ["React", "PHP", "MongoDB"],
    budget: 5000,
    userCreatedId: 5,
  },
];

// initial tasks data
export const initialTasks = [
  {
    id: 1,
    title: "Task 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "High",
    status: "completed",
    projectId: 1,
    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "jane@example.com",
        role: "Designer",
        img: " https://randomuser.me/api/portraits",
      },
      {
        id: "user_id_3",
        name: "John Doe",
        email: "doe@developer.com",
        role: "Developer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
  {
    id: 2,
    title: "Task 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Medium",
    status: "inProgress",
    projectId: 2,
    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "smith@developershipon.com",
        role: "Designer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
  {
    id: 3,
    title: "Task 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Low",
    status: "notStarted",
    projectId: 3,
    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_3",
        name: "John Doe",
        email: "john@gmail.com",
        role: "Developer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
  {
    id: 4,
    title: "Task 4",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Hight",
    status: "testing",
    projectId: 4,
    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "smith@developershipon.com",
        role: "Designer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
  {
    id: 5,
    title: "Task 5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Medium",
    status: "deployment",
    projectId: 5,
    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "smith@developershipon.com",
        role: "Designer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
  {
    id: 6,
    title: "Task 6",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Medium",
    status: "testing",
    projectId: 6,
    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "smith@developershipon.com",
        role: "Designer",
        img: "https://randomuser.me/api/portraits",
      },
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "smith@developershipon.com",
        role: "Designer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
  {
    id: 7,
    title: "Task 7",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    priority: "Hight",
    status: "notStarted",
    projectId: 7,

    dueTime: "2022-12-12",
    attachments: [],
    assignedTo: [
      {
        id: "user_id_2",
        name: "Jane Smith",
        email: "smith@developershipon.com",
        role: "Designer",
        img: "https://randomuser.me/api/portraits",
      },
    ],
  },
];
